spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: kalden
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

    show-sql: true

  application:
    name: hotel-service


server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
