spring:
  config:
    import: configserver:http://localhost:8085

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: kalden
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

    show-sql: true

  application:
    name: hotel-service


server:
  port: 8082
