spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelreviewmicroservice
    username: root
    password: Basketball

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

    show-sql: true

  application:
    name: user-service


server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka