server:
  port: 8081

spring:
  config:
    import: optional:configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/hotelreviewmicroservice
    username: root
    password: Basketball

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true

  application:
    name: user-service
