spring:
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

  application:
    name: rating-service

server:
  port: 8083
